{
    "functionName": "test_defaults_management",
    "className": "TestPibImpl",
    "fileName": "/named-data_&_PyNDN2/tests_&_integration_tests_&_test_pib_impl.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "for fixture in self.pibImpls:\n    pib = fixture.pib\n    pib.addIdentity(fixture.id1)\n    self.assertEqual(fixture.id1, pib.getDefaultIdentity())\n    pib.addIdentity(fixture.id2)\n    self.assertEqual(fixture.id1, pib.getDefaultIdentity())\n    pib.removeIdentity(fixture.id1)\n    try:\n        pib.getDefaultIdentity()\n        self.fail('Did not throw the expected exception')\n    except Pib.Error:\n        pass\n    else:\n        self.fail('Did not throw the expected exception')\n    pib.addKey(fixture.id2, fixture.id2Key1Name, fixture.id2Key1.buf())\n    self.assertEqual(fixture.id2, pib.getDefaultIdentity())\n    self.assertEqual(fixture.id2Key1Name, pib.getDefaultKeyOfIdentity(\n        fixture.id2))\n    pib.addKey(fixture.id2, fixture.id2Key2Name, fixture.id2Key2.buf())\n    self.assertEqual(fixture.id2Key1Name, pib.getDefaultKeyOfIdentity(\n        fixture.id2))\n    pib.removeKey(fixture.id2Key1Name)\n    try:\n        pib.getDefaultKeyOfIdentity(fixture.id2)\n        self.fail('Did not throw the expected exception')\n    except Pib.Error:\n        pass\n    else:\n        self.fail('Did not throw the expected exception')\n    pib.addCertificate(fixture.id2Key2Cert1)\n    self.assertEqual(fixture.id2Key2Name, pib.getDefaultKeyOfIdentity(\n        fixture.id2))\n    self.assertEqual(fixture.id2Key2Cert1.getName(), pib.\n        getDefaultCertificateOfKey(fixture.id2Key2Name).getName())\n    pib.addCertificate(fixture.id2Key2Cert2)\n    self.assertEqual(fixture.id2Key2Cert1.getName(), pib.\n        getDefaultCertificateOfKey(fixture.id2Key2Name).getName())\n    pib.removeCertificate(fixture.id2Key2Cert2.getName())\n    self.assertEqual(fixture.id2Key2Cert1.getName(), pib.\n        getDefaultCertificateOfKey(fixture.id2Key2Name).getName())\n"
}