{
    "functionName": "test_prec_gen_nosteps_exception",
    "className": "TestPrecGenerator",
    "fileName": "/alsprogrammer_&_PythonFuzzyLogic/tests_&_defuzzify_test.py",
    "projectName": "repos",
    "Label": false,
    "isTest": true,
    "Body": "sum = 0\nwith self.assertRaises(ValueError) as context:\n    prec_generator(0, 0, 1).__next__()\nself.assertTrue(isinstance(context.exception, ValueError))\n"
}